name: Build

on:
  push:
    branches: [ 8.xx ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ 8.xx ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: build js-dos
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
    - run: npm install -g yarn
    - run: yarn
    - run: yarn run eslint . --ext ts,tsx --max-warnings 0
    - run: mkdir -p public/emulators && cp -rv node_modules/emulators/dist/* public/emulators
    - run: NODE_ENV=production yarn run vite build --base /latest --sourcemap true --minify terser
    - run: zip -9r release.zip dist/*
    - name: publish
      if: startsWith(github.ref, 'refs/tags/')
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: 'dist'
        path: 'dist'
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ github.ref_name }}
        files: |
          ${{github.workspace}}/release.zip
